services:
      app.controller.homepage:
          class:     kuma\PortfolioBundle\Controller\HomepageController
          arguments: ["@form.factory",'@doctrine.orm.default_entity_manager',"@mailer","@templating"]

      app.controller.articlepage:
          class:     kuma\PortfolioBundle\Controller\ArticleController
          arguments: ['@doctrine.orm.default_entity_manager']


      portfolio.projects.twig.extension:
          class:      kuma\PortfolioBundle\Twig\Extension\ProjectExtension
          arguments: ["@doctrine.orm.entity_manager"]
          tags:
              - { name: twig.extension }

      portfolio.articles.twig.extension:
            class:      kuma\PortfolioBundle\Twig\Extension\ArticleExtension
            arguments: ["@doctrine.orm.entity_manager","@request_stack"]
            tags:
                - { name: twig.extension }

      kumaportfoliobundle.admin.menu.adaptor:
          class:      kuma\PortfolioBundle\Helper\Menu\ModulesMenuAdaptor
          arguments: ["@doctrine.orm.entity_manager"]
          tags:
              - { name: kunstmaan_admin.menu.adaptor }




